# Generated by Django 3.0.5 on 2023-10-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20231029_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
