# Generated by Django 3.0.5 on 2023-10-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20231030_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.DateTimeField(verbose_name='create_at'),
        ),
    ]
